.define gAccTemp   $0006
.define gAccTemp2  $0008
.define gAccTemp3  $000a
.define gTestOut   $0010
.define gFillPos   $0020
.define gPadState  $0030
.define gPadTemp   $0032
.define gLargeWorkArea  $0100
.define gFieldMapArea   $0400


; Game specific variables here

.define gPlayerX4   $0100
.define gPlayerY4   $0102
.define gPlayerVX4  $0104
.define gPlayerVY4  $0106
.define gPlayerFlipY $0108
.define gPlayerFlipX $010a
.define gPlayerAnimationFrame $110
.define gPlayerWalkCount      $112
.define gPlayerHMoveFlag      $114
.define gPlayerOnFloorFlag    $116
.define gPlayerJumpCount      $118
.define gPlayerJumpSuppressRepeat $11a
